In [1]:
import torch
import pandas as pd
import numpy as np
import math
from sklearn.preprocessing import MinMaxScaler

In [2]:
# READ THE DATASET
df = pd.read_csv('diabetes.csv')

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
# CONVERT ALL 0's IN THE TARGET COLUMN TO -1
df.loc[df['Outcome'] == 0, 'Outcome'] = -1

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,-1
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,-1
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# SCALER TO SCALE THE INPUT VALUES IN THE RANGE [-1,1]
scaler = MinMaxScaler(feature_range=(-1, 1))

In [5]:
# GET THE INPUT
x = torch.tensor(scaler.fit_transform(df.drop('Outcome', axis=1)))
# GET THE OUTPUT
y = torch.tensor(df['Outcome'].values)

In [6]:
# LEARNING-RATE / STEP-SIZE
lr = 0.1

# NO. OF ITERATIONS
n_iter = 500

In [7]:
# WEIGHT VECTOR ALSO CONTAINING THE BIAS
# INITIALIZED TO ZERO
w = torch.zeros(x.shape[1]+1, dtype=torch.float64)

In [8]:
# INDICATOR FUNCTION
# IT RETURNS 1 WHEN THE PERCEPTRON MAKES A MISCLASSIFICATION
# OR RETURNS 0 OTHERWISE
def indicator_func(x,y,w):
    if y*(torch.dot(w,x)) <= 0:
        return 1
    else:
        return 0

In [9]:
for _ in range(n_iter):
    # VECTOR USED TO UPDATE THE WEIGHT VECTOR
    weight_update = torch.zeros_like(w)

    for i in range(x.shape[0]):
        # EACH INPUT VECTOR CONCATENATED WITH 1
        xi = torch.cat((x[i],torch.tensor([1])),dim=0)
        # TARGET LABEL
        yi = y[i]
        # VALUE OF INDICATOR FUNCTION
        ind = indicator_func(xi,yi,w)

        # ADD THE PERCEPTRON UPDATES FOR EACH ITERATION
        weight_update = weight_update + (yi*xi*ind)

    # UPDATE THE WEIGHT VECTOR
    w = w + lr*weight_update

In [10]:
# OUTPUT THE WEIGHT VECTOR
w

tensor([ 25.2176,  72.2095, -20.7967,   5.9646,  -1.5891,  54.5951,  29.2184,
         14.3667, -15.5000], dtype=torch.float64)